language: node_js
sudo: 'false'
before_script:
  - npm install -g polymer-cli
node_js: node
addons:
  firefox: latest
script:
  - xvfb-run polymer test --module-resolution=node --npm --local firefox
dist: trusty