language: node_js
node_js:
  - 12
addons:
  firefox: latest
before_script:
  - npm install -g polymer-cli
  - git checkout package-lock.json
node_js: node
script:
  - xvfb-run polymer test --module-resolution=node --npm --local firefox